[Configuration]
loadlastsettingsfile = False
debug = False
clearlogeachrun = True
savepassword = True
networklogging = False
attachmentchunksize = 2097152
proxyaddress = 
proxyusername = 
proxypassword = 
logbuffersize = 1000

[State]
mainframesize = (1012, 575)
settingsfile = /Users/nelson/gitlab/consulting/openEQUELLA-ebi/source/test.ebi

